name: Create promotion pull request
on:
  schedule: 
    # Daily at 8:20 UTC
    - cron: '0 17 * * *'
  push:
    branches:
      - release/v1
jobs:
  promotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git fetch --all
          echo "COMMITS_AHEAD=$(git rev-list --left-right --count origin/release/v2..origin/release/v1 | grep -E '0$' -o)"  >> $GITHUB_ENV
      - name: createPR
        if: ${{ env.COMMITS_AHEAD != '0' }}
        run: gh pr create -B release/v2 -H release/v1 --title 'Merge release/v1 into release/v2' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
