name: Create promotion pull request
on:
  schedule: 
    # Daily at 8:20 UTC
    - cron: '0 14 * * *'
  push:
    branches:
      - release/v1
jobs:
  promotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
#      - name: Reset promotion branch
#        run: git fetch --all
      - run: gh pr create -B release/v2 -H release/v1 --title 'Merge release/v1 into release/v2' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
