name: Create sync pull request
on:
  schedule: 
    # Daily at 8:20 UTC
    - cron: '55 17 * * *'
  push:
    branches:
      - release/v1

env:
  SOURCE: release/v1
  DESTINATION: release/v2
  
jobs:
  promotion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Compare Branches
        run: echo "COMMITS_AHEAD=$(git rev-list --left-right --count origin/$DESTINATION..origin/$SOURCE | grep -E '0$' -o)"  >> $GITHUB_ENV

      - name: Create PR
        if: ${{ env.COMMITS_AHEAD != '0' }}
        run: gh pr create -B $DESTINATION -H $SOURCE --title "Sync $SOURCE to $DESTINATION" --body "Sync $SOURCE to $DESTINATION by Github Action"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
